### ISSUE TITLE
Does this still work with focused tests? i.e. `iit` and `ddescribe`

### ISSUE THREAD

**Issue by elgalu** [nonplus/jasmine-beforeAll#4]
Does this still work with focused tests i.e. `iit` and `ddescribe` ?

So if focus on just 1 test replacing `it` with `iit` will still run the corresponding `beforeAll` if there is one?

Thanks for this repo!

**Comment by nonplus** [comment]
Don't remember testing this, but the way it patches Jasmine, it should still work as expected.

Let me know if it doesn't behave as expected.
